 - name: Fly GitHub Deploy
  # You may pin to the exact commit or the version.
  # uses: dentarg/fly@3c748ba4dd4e5e8ea4279327a871fc6193fe31a2
  uses: dentarg/fly@v1.4.0
  with:
    # Build time variables in the form of NAME=VALUE pairs
    build-args: # optional, default is 
    # Fly API token
    fly-token: FlyV1 fm2_lJPECAAAAAAADrs/xBBUN/K2NR3EeVmwRmXRYGlXwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOABFbxx8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDwvsXzQYzlhmchLHJ1qt5aBgMYD66UsLKoPnCqD1AIsYnKhwUB0fL0BuK96OSkTYPvOHLGTRlQ77xShPH7ETg+OSBzOHqZp8n5pTkIb7hBbyCrES9pPjk0I1mwKe1NF3MHsGrG7wCqlq6IT1e20YTOrv8uWk3mIU/g9eL2/tiGja6tKMic4glIjXUhwoA2SlAORgc4BHvzRHwWRgqdidWlsZGVyH6J3Zx8BxCCUBxZ1SiJGKtdb3YobztTnXTWAFFcQC+PtqR3uxxPe3A==,fm2_lJPETg+OSBzOHqZp8n5pTkIb7hBbyCrES9pPjk0I1mwKe1NF3MHsGrG7wCqlq6IT1e20YTOrv8uWk3mIU/g9eL2/tiGja6tKMic4glIjXUhwoMQQW2xxmIidKZcHL+U3z9/+JMO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5qIFkLzwAAAAEmGHcpF84AEK8nCpHOABCvJwzEEEpcKJo4iQ8dXyTVMmwb5ybEICXCTi6XX/jPeVSbe3fDdsX4FS8krIWKIl2Jcw61+Odm
    # The repo scoped token generated by GitHub Actions
    github-token: # optional
          
